# ===================================================================
# 以composer方式引入时默认的配置
#
# 所有相对路径以bat脚本执行路径为准
# 在Laravel中即项目根目录
# ===================================================================

generator:
  template-path: ./resources/generator
  laravel-path: .
  auto-test-path: .
  doc-path: .
  postman-path: .
  testcases-path: ./resources/generator/testcases
  test-host: http://localhost
